//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosoblspass.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireDispatchSchedule
    {
        public int Id { get; set; }
        public int IdAddress { get; set; }
        public int IdPhoto { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
